In [2]:
import theano.tensor as T
import numpy as np
from theano.tensor.nnet import conv2d
from theano.tensor.signal.pool import pool_2d
# I n p u t s and w e i g t h s f o r c o n v o l u t i o n
#a= np.random.randint(−100,100, size =[1 ,3 ,4 ,4])
a = np.random.randint(-100,100, size =[1,1,4 ,4])
print('a',a)
w= np.random.rand(1,1,2,2)
print('w',w)
# C o n v o l u t i o n

l1 = conv2d(a.astype(float), w.astype(float))
print('convolution',l1.eval())
# ReLU
l2 = T.maximum (0,l1)
print('ReLU',l2.eval())
#Max p o o l
l3 = pool_2d (l2 , (2 ,2))
print('max pool',l3.eval())


l4 = T.flatten(l3, 1)
print('flatten',l4.eval())

l5 = l3.flatten(1)
print('flatten',l5.eval())

a [[[[  7  59 -32  -6]
   [ 30 -24 -47  36]
   [ 97 -74 -19 -60]
   [-44 -56  26 -74]]]]
w [[[[0.30674558 0.67278351]
   [0.40134073 0.83715056]]]]


WARNING (theano.tensor.blas): We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.


convolution [[[[ 42.36076825   5.9851331  -49.77484641]
   [ 58.04316708 -94.56877345 -56.08543151]
   [  4.72416328 -99.27510667 -45.19310576]]]]
ReLU [[[[42.36076825  5.9851331   0.        ]
   [58.04316708  0.          0.        ]
   [ 4.72416328  0.          0.        ]]]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: UserWarning: pool_2d() will have the parameter ignore_border default value changed to True (currently False). To have consistent behavior with all Theano version, explicitly add the parameter ignore_border=True. On the GPU, using ignore_border=True is needed to use cuDNN. When using ignore_border=False and not using cuDNN, the only GPU combination supported is when `ws == stride and pad == (0, 0) and mode == 'max'`. Otherwise, the convolution will be executed on CPU.


max pool [[[[58.04316708  0.        ]
   [ 4.72416328  0.        ]]]]
flatten [58.04316708  0.          4.72416328  0.        ]
flatten [58.04316708  0.          4.72416328  0.        ]


In [20]:
import theano.tensor as T
import numpy as np
from theano.tensor.nnet import conv2d
from theano.tensor.signal.pool import pool_2d

x = np.random.randint(0,5, size =[1,1,5,5])
print('a',x)

w1= np.random.randint(-5,5, size =[2,1,3,3])
print('w',w1)
print(w1.shape)

b1 = np.ones(shape=(1,1,3,3))
print('b1',b1)

xw1 = conv2d(x.astype(float), w1.astype(float))
print('xw1',xw1.eval())

X1= xw1 + b1
print('X1',X1.eval())

rl1 = T.nnet.relu(X1)
print('rl1',rl1.eval())

x2flat = np.random.randint(0,5, size =[1,1,1,2])
print('x2flat', x2flat)

w2 = np.random.randint(0,5, size =[1,1,2,2])
print('w2', w2)

x3 = T.dot(x2flat,w2)
print('x3',x3.eval())

b2 = np.ones(shape=(1,1,1,2))
print('b2',b2)

rl2 = T.nnet.relu(x3+b2)[0][0]
print('rl2',rl2.eval())

w3 = np.random.randint(-50,50, size =[1,1,2,10])
print('w3', w3)

rl2 = np.random.randint(-50,50, size =[1,1,1,2])
print('rl2', rl2)

x4= np.dot(rl2,w3)
print('x4',x4)

x4R = T.nnet.relu(x4)[0][0]
print('x4R',x4R)

output = T.nnet.softmax(x4R[0][0])
print(output.eval())


a [[[[0 3 1 1 3]
   [4 4 3 3 2]
   [1 4 4 3 3]
   [0 4 1 3 2]
   [1 1 4 1 1]]]]
w [[[[ 2 -2  3]
   [ 1  4 -1]
   [-5  3 -3]]]


 [[[ 2 -4 -5]
   [ 3 -5  1]
   [ 3  2  3]]]]
(2, 1, 3, 3)
b1 [[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]
xw1 [[[[ 22.  10.   8.]
   [ -2.  13.   2.]
   [ 15. -15.   7.]]

  [[-11. -18. -18.]
   [  8.   2.   6.]
   [  5.  18.  -3.]]]]
X1 [[[[ 23.  11.   9.]
   [ -1.  14.   3.]
   [ 16. -14.   8.]]

  [[-10. -17. -17.]
   [  9.   3.   7.]
   [  6.  19.  -2.]]]]
rl1 [[[[23. 11.  9.]
   [ 0. 14.  3.]
   [16.  0.  8.]]

  [[ 0.  0.  0.]
   [ 9.  3.  7.]
   [ 6. 19.  0.]]]]
x2flat [[[[3 4]]]]
w2 [[[[2 2]
   [2 2]]]]
x3 [[[[[[14 14]]]]]]
b2 [[[[1. 1.]]]]
rl2 [[[[15. 15.]]]]
w3 [[[[-49 -38  17 -34 -28 -43 -23 -17 -42  -2]
   [ 17  30  34  23  29  30 -25 -45  22 -17]]]]
rl2 [[[[-43  38]]]]
x4 [[[[[[2753 2774  561 2336 2306 2989   39 -979 2642 -560]]]]]]
x4R [[[[2753. 2774.  561. 2336. 2306. 2989.   39.    0. 2642.    0.]]]]
[[3.20997959e-103 4.23337159e-094 0.00000000

In [80]:
w3 = np.random.randint(-50,50, size =[2,10])
print('w3', w3)


rl2 = np.random.randint(-50,50, size =[1,2])
print('rl2', rl2)


x4= np.dot(rl2,w3)
print('x4',x4)

w3 [[-17   5  32   0  -3  18  23  10  16 -16]
 [-34 -32  11  11 -34 -17  24 -32 -45 -29]]
rl2 [[  5 -34]]
x4 [[1071 1113 -214 -374 1141  668 -701 1138 1610  906]]


In [28]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data( )

11493376/11490434 [==============================] - 0s 0us/step


In [29]:
x_train.shape

(60000, 28, 28)

In [30]:
x_test.shape

(10000, 28, 28)

In [36]:
train_set_y.eval()

array([5, 0, 4, ..., 5, 6, 8], dtype=int32)

In [40]:
visible_size= (28,28)


In [45]:
x_train[0].shape

(28, 28)

In [47]:
x=np.reshape(x_train[0],(1,1,28,28))

In [48]:
x.shape

(1, 1, 28, 28)

In [42]:
n_train_batches = x_train[0]/batch_size

In [32]:
train_set_x = theano.shared(value=x_train, name='train_set_x')
train_set_y = T.cast(theano.shared(value=y_train, name='train_set_y'), 'int32')

In [55]:
 import warnings
warnings.filterwarnings('ignore')

import numpy as np
import matplotlib.pyplot as plt
import os, struct
from array import array as pyarray
from numpy import append, array, int8, uint8, zeros

import tensorflow as tf
print(tf.__version__)


import theano.tensor as T
import theano.tensor.signal 
from theano.tensor.signal.pool import pool_2d
import numpy as np

learning_rate = T.scalar('lr')
index = T.lscalar('index')
batch_size = 100

print('learning rate', learning_rate)
print('index', index)
print('batch_size',batch_size)

#train_set_x = theano.shared(value=images, name='train_set_x')
#train_set_y = T.cast(theano.shared(value=label, name='train_set_y'), 'int32')

#visible_size= (images.shape[2],images.shape[3])
hidden_units=100
output_units=10
rng = np.random.RandomState(1242)
epochs = 10
learn_rate = 0.002

print('otros datos')
print(hidden_units)
print(output_units)
print(rng)
print(epochs)
print(learn_rate)

########################################
##########INPUTS AND WEIGHTS############
########################################
#x = T.tensor4('x')
#output
y = T.ivector('y')


#input weights for the weight matrices are rather important; if they are not set correctly, results might get stuck in local minima
Wc0 = theano.shared(value=np.asarray(rng.uniform(low=-0.035,high=0.035,size=(32,1,3,3)),dtype=theano.config.floatX), name='Wc0')
bc0 = theano.shared(value=np.zeros((32,),dtype=theano.config.floatX), name='bc0')

Wc1 = theano.shared(value=np.asarray(rng.uniform(low=-0.035,high=0.035,size=(64,32,4,4)),dtype=theano.config.floatX), name='Wc1')
bc1 = theano.shared(value=np.zeros((64,),dtype=theano.config.floatX), name='bc1')

print('Wc0',Wc0.eval().shape)
print('Wc0',Wc0.eval().shape)
print('bc0',bc0.eval().shape)
print('Wc1',Wc1.eval().shape)
print('bc1',bc1.eval().shape)

#weights first layer
W1 = theano.shared(value=np.asarray(rng.uniform(low=-0.01,high=0.01,size=(64*5*5,hidden_units)),dtype=theano.config.floatX), name='W1')
#bias first layer
b1 = theano.shared(value=np.zeros((hidden_units,),dtype=theano.config.floatX), name='b1')
#weights second layer
W2 = theano.shared(value=np.asarray(rng.uniform(low=-0.05,high=0.05,size=(hidden_units,output_units)),dtype=theano.config.floatX), name='W2')
#bias second layer
b2 = theano.shared(value=np.zeros((output_units,),dtype=theano.config.floatX), name='b2')

print('W1',W1.eval().shape)
print('b1',b1.eval().shape)
print('W2',W2.eval().shape)
print('b2',b2.eval().shape)

########################################
##############  NETWORK  ###############
########################################


conv1Out = T.maximum(0,(T.nnet.conv.conv2d(x, Wc0)+bc0.dimshuffle('x', 0, 'x', 'x')))
print('conv1Out', conv1Out.eval())

maxPool1Out= pool_2d(conv1Out, (2,2))
print(maxPool1Out)
conv2Out = T.maximum(0,(T.nnet.conv.conv2d(maxPool1Out, Wc1)+bc1.dimshuffle('x', 0, 'x', 'x')))
print(conv2Out)
maxPool2Out= pool_2d(conv2Out, (2,2))
print(maxPool2Out)
flattenOut = maxPool2Out.flatten(2)
print(flattenOut)
denselyConnected1Out = T.nnet.sigmoid(T.dot(flattenOut, W1)+b1)
print(denselyConnected1Out)
denselyConnected2Out = T.nnet.softmax(T.dot(denselyConnected1Out, W2)+b2)
print(denselyConnected2Out)
loss = -T.mean(T.log(denselyConnected2Out)[T.arange(y.shape[0]), y])
print(loss)

prediction = T.argmax(denselyConnected2Out,axis=1)
print(prediction)
predict = theano.function([x], prediction)
print(predict)

########################################
#######  GRADIENT AND UPDATES  #########
########################################
params = [Wc0,bc0,Wc1,bc1,W1,b1,W2,b2]
gradient = T.grad(loss, params)
updates = []
for p, g in zip(params, gradient):
   updates.append((p, p - learning_rate * g))

#train = theano.function([index, learning_rate], loss, updates=updates,
#     givens = {x: train_set_x[(index * batch_size): ((index + 1) * batch_size)],
#               y: train_set_y[(index * batch_size): ((index + 1) * batch_size)]})



2.3.0
learning rate lr
index index
batch_size 100
otros datos
100
10
RandomState(MT19937)
10
0.002
Wc0 (32, 1, 3, 3)
Wc0 (32, 1, 3, 3)
bc0 (32,)
Wc1 (64, 32, 4, 4)
bc1 (64,)
W1 (1600, 100)
b1 (100,)
W2 (100, 10)
b2 (10,)


MissingInputError: ignored

In [ ]:
for epoch in range(epochs):
    # go through training set
    c = []
    for batch_index in range(int(n_train_batches)):
        c.append(train(batch_index, learn_rate))

    predictions_test = predict(test_images)
    accuracy = np.mean(predictions_test == test_label)
    print("epoch",epoch,"| loss", np.mean(c),"| accuracy: %.5f" % accuracy)